### PR TITLE
Allow strings to contain dots, but not start with them

### PR DESCRIPTION
**Pull request by vanstee**
Fixes https://github.com/operable/cog/issues/584

### CODE REVIEW

**Comment by christophermaier** [comment]
It looks like this allows a _name_ to contain a `.`, not a _string_... is that correct, or am I missing something about how Piper parses things?

**Comment by vanstee** [comment]
@christophermaier Yeah it is a little weird how that works. But down in the rules section it actually gets tokenized as a string https://github.com/operable/piper/blob/master/lib/piper/command/piper_cmd_lexer.xrl#L52

**Comment by christophermaier** [comment]
Does that actually address the situation described in https://github.com/operable/cog/issues/584? I didn't think that parsed as a "name".

**Comment by vanstee** [comment]
All non-quoted strings match the `NAME` definition, which are then immediately tokenized as strings. So no, they aren't parsed as names, since the parser just sees a string token and doesn't know about the `NAME` definition at all.

**Comment by vanstee** [comment]
It's pretty weird, and I think it should probably change eventually, just not really sure of the reason for the name `NAME` there. @kevsmith probably knows the history for that decision.

**Comment by christophermaier** [comment]
@vanstee OK, fair enough... looks like there are holes in my understanding, so I'll defer to you and @kevsmith.

As far as my understanding goes, as well as what you've explained here, this looks 👍 , for what it's worth.

**Comment by vanstee** [comment]
Merging, but I'll go over this with @kevsmith and just make sure I understand it correctly.

**Pull request merged**
